"""Phase 5: DOCUMENT — generate README and documentation."""

from pathlib import Path

from mcp_anything.codegen.emitter import Emitter
from mcp_anything.pipeline.context import PipelineContext
from mcp_anything.pipeline.phase import Phase


class DocumentPhase(Phase):
    @property
    def name(self) -> str:
        return "document"

    def validate_preconditions(self, ctx: PipelineContext) -> list[str]:
        if not ctx.manifest.design:
            return ["Design phase must complete before documentation"]
        return []

    async def execute(self, ctx: PipelineContext) -> None:
        design = ctx.manifest.design
        assert design is not None

        output_dir = Path(ctx.manifest.output_dir)
        emitter = Emitter(design, output_dir)

        if getattr(ctx.options, "target", "fastmcp") == "mcp-use":
            # TypeScript target: README is generated by the package phase; only emit AGENTS.md
            ctx.console.print("    Generating documentation (TypeScript/mcp-use)...")
            generated = emitter.emit_agents_only()
            # Append a TypeScript-specific usage note to AGENTS.md
            if generated:
                agents_path = output_dir / "AGENTS.md"
                existing = agents_path.read_text()
                note = (
                    "\n## Runtime\n\n"
                    "This server is generated for the **TypeScript / mcp-use** target.\n\n"
                    "```bash\n"
                    "npm install && npm run dev\n"
                    "```\n\n"
                    "Inspector: http://localhost:3000/inspector\n"
                )
                agents_path.write_text(existing + note)
        else:
            ctx.console.print("    Generating documentation...")
            generated = emitter.emit_docs()

        ctx.manifest.generated_files.extend(generated)
        ctx.console.print(f"    Generated {len(generated)} doc files")
