"""Scope filtering for capability curation.

Supports three mechanisms:
1. --include/--exclude glob patterns on the CLI
2. --review mode: write a scope.yaml after ANALYZE, pause for user editing
3. --scope-file: load a pre-existing scope file
"""

import fnmatch
from pathlib import Path
from typing import Optional

import yaml

from mcp_anything.models.analysis import AnalysisResult, Capability


def write_scope_file(analysis: AnalysisResult, path: Path) -> None:
    """Write a scope.yaml from analysis results for user review."""
    entries = []
    for cap in analysis.capabilities:
        entry: dict = {
            "name": cap.name,
            "description": cap.description,
        }
        if cap.source_file:
            entry["source"] = cap.source_file
        if cap.category and cap.category != "general":
            entry["category"] = cap.category
        entries.append(entry)

    doc = {
        "include_patterns": [],
        "exclude_patterns": [],
        "capabilities": entries,
    }

    header = (
        "# Generated by mcp-anything analyze --review\n"
        "# Edit this file to control which capabilities become MCP tools.\n"
        "#\n"
        "# Quick filters (glob patterns matched against capability name, source path,\n"
        "# and description):\n"
        "#   include_patterns: [\"/api/v2/*\"]   — only matching capabilities\n"
        "#   exclude_patterns: [\"/internal/*\"]  — skip matching capabilities\n"
        "#\n"
        "# Per-capability control:\n"
        "#   enabled: false  — always excluded (overrides include patterns)\n"
        "#   enabled: true   — always included (overrides exclude patterns)\n"
        "#   (omitted)       — patterns decide\n"
        "#\n"
        "# After editing, run: mcp-anything generate <path> --resume\n"
        "\n"
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.write(header)
        yaml.dump(doc, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def read_scope_file(path: Path) -> dict:
    """Read and validate a scope.yaml file."""
    with open(path) as f:
        doc = yaml.safe_load(f)

    if not isinstance(doc, dict):
        raise ValueError(f"Invalid scope file: expected a YAML mapping, got {type(doc).__name__}")

    return doc


def apply_scope(
    analysis: AnalysisResult,
    *,
    include_patterns: Optional[list[str]] = None,
    exclude_patterns: Optional[list[str]] = None,
    include_annotation: Optional[list[str]] = None,
    exclude_annotation: Optional[list[str]] = None,
    scope_file: Optional[Path] = None,
) -> AnalysisResult:
    """Filter analysis capabilities based on scope rules.

    Priority order:
    1. Annotation filters (include_annotation / exclude_annotation)
    2. scope_file per-capability enabled/disabled flags (most specific)
    3. scope_file include/exclude patterns
    4. CLI --include/--exclude patterns (additive with scope_file patterns)

    Returns a new AnalysisResult with filtered capabilities.
    """
    # 1. Apply annotation filters first
    filtered: list[Capability] = list(analysis.capabilities)
    
    if include_annotation:
        # All specified annotations must be present
        for ann in include_annotation:
            filtered = [c for c in filtered if ann in c.annotations]
    
    if exclude_annotation:
        # None of the excluded annotations should be present
        for ann in exclude_annotation:
            filtered = [c for c in filtered if ann not in c.annotations]

    # Merge patterns from scope file and CLI
    all_include: list[str] = list(include_patterns or [])
    all_exclude: list[str] = list(exclude_patterns or [])

    # Per-capability overrides from scope file
    # Three states: True (force include), False (force exclude), None (patterns decide)
    cap_override: dict[str, bool | None] = {}

    if scope_file and scope_file.exists():
        doc = read_scope_file(scope_file)
        all_include.extend(doc.get("include_patterns") or [])
        all_exclude.extend(doc.get("exclude_patterns") or [])

        for entry in doc.get("capabilities") or []:
            if isinstance(entry, dict) and "name" in entry:
                if "enabled" in entry:
                    cap_override[entry["name"]] = bool(entry["enabled"])
                else:
                    cap_override[entry["name"]] = None

    result: list[Capability] = []
    for cap in filtered:
        # Check per-capability override first (most specific)
        if cap.name in cap_override and cap_override[cap.name] is not None:
            if not cap_override[cap.name]:
                continue
            # Explicitly enabled — skip pattern checks
            result.append(cap)
            continue

        # Build match targets: capability name, source file, description, HTTP path
        targets = [cap.name]
        if cap.source_file:
            targets.append(cap.source_file)
        if cap.description:
            targets.append(cap.description)
        if cap.http_path:
            targets.append(cap.http_path)

        # Include patterns: at least one target must match at least one pattern
        if all_include:
            matched = any(
                fnmatch.fnmatch(target, pattern)
                for target in targets
                for pattern in all_include
            )
            if not matched:
                continue

        # Exclude patterns: skip if any target matches any pattern
        if all_exclude:
            excluded = any(
                fnmatch.fnmatch(target, pattern)
                for target in targets
                for pattern in all_exclude
            )
            if excluded:
                continue

        result.append(cap)

    # Return a copy with filtered capabilities
    return analysis.model_copy(update={"capabilities": result})
